### ISSUE TITLE
Limit repos for -R User/*

### ISSUE THREAD

**Issue by RichardLitt** [octoherd/script-rename-master-branch-to-main#5]
**What happened?**

When running `-R "RichardLitt/*"`, all of the repos in an organization came up, instead of merely RichardLitt/* repos. 

**What did you expect to happen?**

Only repos under my namespace should be changed.

**Comment by oscard0m** [comment]
Hi @RichardLitt ,

Sorry for the late reply here. I think I'm not understanding your issue. Could you provide a list of repository links where I can understand the issue? (they do not need to be real, just an example):

i.e.
- https://github.com/MyAwesomeOrg/repo1
- https://github.com/MyAwesomeOrg/repo2
- https://github.com/MyAwesomeOrg/repo3

**Comment by RichardLitt** [comment]
I can't - this was too long ago and I don't remember. Thanks.
